
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Important: Add these environment variables in the Netlify dashboard
# under Site settings > Build & deploy > Environment variables:
# - VITE_CLERK_PUBLISHABLE_KEY (Required for authentication)
# - VITE_FLUTTERWAVE_PUBLIC_KEY (Required for payments)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
