
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Important: Add VITE_CLERK_PUBLISHABLE_KEY in the Netlify dashboard
# under Site settings > Build & deploy > Environment variables

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
