
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# CRITICAL ENVIRONMENT VARIABLES:
# ===============================
# VITE_CLERK_PUBLISHABLE_KEY - REQUIRED for authentication - MUST BE SET IN NETLIFY ENV VARIABLES
#   * Without this key, authentication will fall back to demo mode
#   * Get your key from https://clerk.com/
#
# Other environment variables:
# VITE_SUPABASE_URL - Required for database access
# VITE_SUPABASE_ANON_KEY - Required for database access
# VITE_FLUTTERWAVE_PUBLIC_KEY - Required for payments (if using payments)

# IMPORTANT: Set these environment variables in the Netlify dashboard:
# Site settings > Build & deploy > Environment > Environment variables

# Add a build plugin to check for required environment variables
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# For local development, create a .env.local file with these variables
# Example:
# VITE_CLERK_PUBLISHABLE_KEY=pk_test_YOURKEY
# VITE_SUPABASE_URL=https://yourproject.supabase.co
# VITE_SUPABASE_ANON_KEY=yourkey

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
