// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytcpgoyldllvumfmieas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0Y3Bnb3lsZGxsdnVtZm1pZWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTg3MzYsImV4cCI6MjA2MDA5NDczNn0.yBkDez-KnA2IgFSLUdno_BiqD7FXgvRLQ7PpCQ2IHHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);